#include <windows.h>
#include <d3d11.h>
#include <commdlg.h>
#include <shlobj.h>
#include <gdiplus.h>

#include <filesystem>
#include <fstream>
#include <memory>
#include <string>
#include <algorithm>

#include "imgui.h"
#include "imgui_impl_dx11.h"
#include "imgui_impl_win32.h"
#include "app_services.h"
#include "dqn_agent.h"
#include "../Backend C/fishing_engine.h"

extern LRESULT ImGui_ImplWin32_WndProcHandler(HWND, UINT, WPARAM, LPARAM);
namespace {
ID3D11Device* device = nullptr; ID3D11DeviceContext* context = nullptr; IDXGISwapChain* swapchain = nullptr; ID3D11RenderTargetView* target = nullptr;
void create_target(){ID3D11Texture2D* back=nullptr;swapchain->GetBuffer(0,IID_PPV_ARGS(&back));device->CreateRenderTargetView(back,nullptr,&target);back->Release();}
void destroy_target(){if(target){target->Release();target=nullptr;}}
bool create_device(HWND window){DXGI_SWAP_CHAIN_DESC d{};d.BufferCount=2;d.BufferDesc.Format=DXGI_FORMAT_R8G8B8A8_UNORM;d.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;d.OutputWindow=window;d.SampleDesc.Count=1;d.Windowed=TRUE;d.SwapEffect=DXGI_SWAP_EFFECT_DISCARD;UINT flags=0;D3D_FEATURE_LEVEL level;return SUCCEEDED(D3D11CreateDeviceAndSwapChain(nullptr,D3D_DRIVER_TYPE_HARDWARE,nullptr,flags,nullptr,0,D3D11_SDK_VERSION,&d,&swapchain,&device,&level,&context));}
void destroy_device(){destroy_target();if(swapchain)swapchain->Release();if(context)context->Release();if(device)device->Release();}
bool choose_file(HWND owner,wchar_t* path,DWORD flags){OPENFILENAMEW o{};o.lStructSize=sizeof(o);o.hwndOwner=owner;o.lpstrFile=path;o.nMaxFile=MAX_PATH;o.lpstrFilter=L"Images (*.png;*.jpg;*.jpeg;*.bmp)\0*.png;*.jpg;*.jpeg;*.bmp\0All files\0*.*\0";o.Flags=flags;return GetOpenFileNameW(&o)!=FALSE;}
bool choose_folder(HWND owner,wchar_t* output){BROWSEINFOW b{};b.hwndOwner=owner;b.lpszTitle=L"Выберите папку с датасетом";PIDLIST_ABSOLUTE p=SHBrowseForFolderW(&b);if(!p)return false;const bool ok=SHGetPathFromIDListW(p,output)!=FALSE;CoTaskMemFree(p);return ok;}
std::string utf8(const std::wstring& value){if(value.empty())return {};const int bytes=WideCharToMultiByte(CP_UTF8,0,value.data(),int(value.size()),nullptr,0,nullptr,nullptr);std::string result(bytes,'\0');WideCharToMultiByte(CP_UTF8,0,value.data(),int(value.size()),result.data(),bytes,nullptr,nullptr);return result;}
ID3D11ShaderResourceView* load_avatar_texture(const std::wstring& path){if(path.empty())return nullptr;Gdiplus::Bitmap source(path.c_str());if(source.GetLastStatus()!=Gdiplus::Ok)return nullptr;const auto format=static_cast<Gdiplus::PixelFormat>(PixelFormat32bppARGB);Gdiplus::Bitmap bitmap(96,96,format);Gdiplus::Graphics graphics(&bitmap);graphics.SetInterpolationMode(Gdiplus::InterpolationModeHighQualityBicubic);graphics.DrawImage(&source,0,0,96,96);Gdiplus::Rect area(0,0,96,96);Gdiplus::BitmapData data{};if(bitmap.LockBits(&area,Gdiplus::ImageLockModeRead,format,&data)!=Gdiplus::Ok)return nullptr;D3D11_TEXTURE2D_DESC desc{};desc.Width=96;desc.Height=96;desc.MipLevels=1;desc.ArraySize=1;desc.Format=DXGI_FORMAT_B8G8R8A8_UNORM;desc.SampleDesc.Count=1;desc.Usage=D3D11_USAGE_DEFAULT;desc.BindFlags=D3D11_BIND_SHADER_RESOURCE;D3D11_SUBRESOURCE_DATA initial{};initial.pSysMem=data.Scan0;initial.SysMemPitch=data.Stride;ID3D11Texture2D* texture=nullptr;const bool ok=SUCCEEDED(device->CreateTexture2D(&desc,&initial,&texture));bitmap.UnlockBits(&data);if(!ok)return nullptr;ID3D11ShaderResourceView* view=nullptr;device->CreateShaderResourceView(texture,nullptr,&view);texture->Release();return view;}
}

class NativeApp {
    HWND window_; std::filesystem::path dir_; std::unique_ptr<AccountService> accounts_; std::unique_ptr<TicketService> tickets_;
    FishingEngine engine_; DqnAgent agent_; bool active_=false, login_=true; int page_=0, theme_=0; float page_alpha_=1.0f; std::string notice_; ID3D11ShaderResourceView* avatar_=nullptr;
    char username_[64]{}, password_[64]{}, promo_[64]{}, dataset_[MAX_PATH]{}, ticket_title_[128]{}, ticket_category_[64]{"Предложение"}, ticket_text_[512]{};
    std::wstring user_;
public:
    explicit NativeApp(HWND w):window_(w){wchar_t path[MAX_PATH]{};GetModuleFileNameW(nullptr,path,MAX_PATH);dir_=std::filesystem::path(path).parent_path();accounts_=std::make_unique<AccountService>(dir_);tickets_=std::make_unique<TicketService>(dir_);restore_session();}
    ~NativeApp(){if(avatar_)avatar_->Release();}
    void restore_session(){std::wifstream file(dir_/L"session.dat");std::wstring saved;if(std::getline(file,saved)&&accounts_->subscription_active(saved)){user_=saved;login_=false;reload_avatar();notice_="Session restored.";}}
    void save_session()const{std::wofstream file(dir_/L"session.dat",std::ios::trunc);file<<user_;}
    void clear_session()const{std::error_code error;std::filesystem::remove(dir_/L"session.dat",error);}
    void reload_avatar(){if(avatar_){avatar_->Release();avatar_=nullptr;}avatar_=load_avatar_texture(accounts_->avatar_path(user_));}
    void style(){ImGuiStyle& s=ImGui::GetStyle();s.WindowRounding=14;s.ChildRounding=12;s.FrameRounding=9;s.GrabRounding=9;s.PopupRounding=10;s.WindowBorderSize=0;s.FrameBorderSize=0;s.ItemSpacing={10,10};s.WindowPadding={18,18};ImVec4* c=s.Colors;const bool ocean=theme_==1,light=theme_==2;c[ImGuiCol_WindowBg]=light?ImVec4(.94f,.96f,.99f,1):ocean?ImVec4(.035f,.09f,.14f,1):ImVec4(.045f,.055f,.08f,1);c[ImGuiCol_ChildBg]=light?ImVec4(1,1,1,.94f):ocean?ImVec4(.07f,.16f,.23f,.86f):ImVec4(.09f,.11f,.16f,.88f);c[ImGuiCol_Button]=light?ImVec4(.12f,.47f,.58f,1):ocean?ImVec4(.05f,.55f,.75f,1):ImVec4(.16f,.68f,.57f,1);c[ImGuiCol_ButtonHovered]=ImVec4(.25f,.75f,.68f,1);c[ImGuiCol_Text]=light?ImVec4(.07f,.1f,.16f,1):ImVec4(.92f,.95f,.98f,1);c[ImGuiCol_TextDisabled]=light?ImVec4(.35f,.4f,.5f,1):ImVec4(.52f,.58f,.67f,1);c[ImGuiCol_FrameBg]=light?ImVec4(.9f,.93f,.97f,1):ImVec4(.13f,.16f,.22f,1);}
    void dashboard(){const bool dev=accounts_->is_developer(user_);const char* labels[]={"Fishing","AI & Dataset","Subscription","Support","Settings","Admin"};const int total=dev?6:5;ImGui::SetNextWindowPos({0,0});ImGui::SetNextWindowSize(ImGui::GetIO().DisplaySize);ImGui::Begin("##main",nullptr,ImGuiWindowFlags_NoDecoration|ImGuiWindowFlags_NoMove);ImGui::BeginChild("sidebar",{220,0},true);ImGui::TextColored(ImVec4(.3f,.85f,.72f,1),"MAJESTIC");ImGui::TextDisabled("AI FISHER");ImGui::Separator();for(int i=0;i<total;i++){if(ImGui::Selectable(labels[i],page_==i,0,{0,38})){page_=i;page_alpha_=0.55f;}}ImGui::SetCursorPosY(ImGui::GetWindowHeight()-142);ImGui::Separator();if(avatar_){ImGui::Image((ImTextureID)avatar_,{46,46});ImGui::SameLine();}ImGui::BeginGroup();ImGui::Text("%s",utf8(user_).c_str());ImGui::TextDisabled(dev?"Developer · lifetime":"Subscription active");ImGui::EndGroup();if(ImGui::Button("Log out",{178,30})){engine_.stop();active_=false;login_=true;page_=0;username_[0]=password_[0]=0;clear_session();if(avatar_){avatar_->Release();avatar_=nullptr;}notice_.clear();}ImGui::EndChild();ImGui::SameLine();ImGui::BeginChild("content",{0,0},true);page_alpha_=std::min(1.0f,page_alpha_+ImGui::GetIO().DeltaTime*4.5f);ImGui::PushStyleVar(ImGuiStyleVar_Alpha,page_alpha_);ImGui::Text("%s",labels[page_]);ImGui::SameLine();ImGui::TextDisabled("/ Native workspace");ImGui::Separator();if(!notice_.empty()){ImGui::PushStyleColor(ImGuiCol_Text,ImVec4(.35f,.85f,.7f,1));ImGui::TextWrapped("%s",notice_.c_str());ImGui::PopStyleColor();}if(page_==0)fish();if(page_==1)ai();if(page_==2)subscription();if(page_==3)support();if(page_==4)settings();if(page_==5&&dev)admin();ImGui::PopStyleVar();ImGui::EndChild();ImGui::End();}
    void fish(){ImGui::BeginChild("fishcard",{0,185},true);ImGui::Text("Automation engine");ImGui::TextDisabled("Native screen analysis and direct input. F5 is supported by the engine.");ImGui::Spacing();if(ImGui::Button(active_?"Stop engine":"Start engine",{210,42})){active_=!active_;if(active_){engine_.start_thread();engine_.set_active(true);notice_="Engine is active — looking for GTA / Majestic.";}else{engine_.stop();notice_="Engine stopped.";}}ImGui::SameLine();ImGui::TextColored(active_?ImVec4(.3f,.9f,.65f,1):ImVec4(.9f,.4f,.45f,1),active_?"● ACTIVE":"● OFFLINE");ImGui::EndChild();ImGui::Spacing();ImGui::Text("Capture zone");float zone[]={float(engine_.scale_x),float(engine_.scale_y),float(engine_.scale_w),float(engine_.scale_h)};if(ImGui::SliderFloat4("X / Y / W / H",zone,0.f,1.f,"%.2f")){engine_.scale_x=zone[0];engine_.scale_y=zone[1];engine_.scale_w=zone[2];engine_.scale_h=zone[3];}}
    void ai(){ImGui::BeginChild("aicard",{0,0},true);ImGui::Text("DQN model");ImGui::TextDisabled("Replay buffer: %zu · exploration: %.2f",agent_.memory_size(),agent_.epsilon());if(ImGui::Button("Save native model"))notice_=agent_.save(dir_/L"dqn_model.bin")?"AI model saved.":"Unable to save AI model.";ImGui::SameLine();if(ImGui::Button("Load native model"))notice_=agent_.load(dir_/L"dqn_model.bin")?"AI model loaded.":"dqn_model.bin was not found.";ImGui::Separator();ImGui::Text("Dataset location");ImGui::InputText("##dataset",dataset_,MAX_PATH);ImGui::SameLine();if(ImGui::Button("Browse")){wchar_t p[MAX_PATH]{};if(choose_folder(window_,p)){WideCharToMultiByte(CP_UTF8,0,p,-1,dataset_,MAX_PATH,nullptr,nullptr);notice_="Dataset folder selected.";}}ImGui::TextDisabled("The folder is ready for native dataset tooling; live fishing continues to train the DQN safely.");ImGui::EndChild();}
    void subscription(){ImGui::BeginChild("subcard",{0,0},true);const bool dev=accounts_->is_developer(user_);ImGui::Text(dev?"Lifetime developer subscription":"Subscription management");ImGui::TextDisabled(dev?"This account has permanent access.":"Enter a promo code to extend access.");if(!dev){ImGui::InputText("Promo code",promo_,sizeof(promo_));if(ImGui::Button("Activate promo")){wchar_t w[64]{};MultiByteToWideChar(CP_UTF8,0,promo_,-1,w,64);std::wstring m;accounts_->activate_promo(user_,w,m);notice_=std::string(m.begin(),m.end());}}ImGui::EndChild();}
    void support(){ImGui::BeginChild("supportcard",{0,0},true);ImGui::Text("Send feedback to the team");ImGui::TextDisabled("Bug report, improvement idea, payment issue, or another question.");ImGui::InputText("Title",ticket_title_,sizeof(ticket_title_));ImGui::InputText("Category",ticket_category_,sizeof(ticket_category_));ImGui::InputTextMultiline("Message",ticket_text_,sizeof(ticket_text_),{0,130});if(ImGui::Button("Create ticket",{170,38})){wchar_t a[128]{},b[64]{},c[512]{};MultiByteToWideChar(CP_UTF8,0,ticket_title_,-1,a,128);MultiByteToWideChar(CP_UTF8,0,ticket_category_,-1,b,64);MultiByteToWideChar(CP_UTF8,0,ticket_text_,-1,c,512);std::wstring m;tickets_->create(user_,a,c,b,m);notice_=std::string(m.begin(),m.end());ticket_title_[0]=ticket_text_[0]=0;}ImGui::Separator();auto list=tickets_->list(user_,accounts_->is_developer(user_));ImGui::Text("Tickets: %zu",list.size());for(const auto&t:list)ImGui::BulletText("#%ls · %ls · %ls",t.id.c_str(),t.category.c_str(),t.title.c_str());ImGui::EndChild();}
    void admin(){ImGui::BeginChild("admincard",{0,0},true);auto list=tickets_->list(user_,true);ImGui::Text("Support inbox");ImGui::TextDisabled("All messages from users are visible here.");ImGui::Separator();for(const auto&t:list){const auto title=utf8(std::wstring(L"#")+t.id+L" · "+t.title);ImGui::PushID(title.c_str());if(ImGui::CollapsingHeader(title.c_str())){ImGui::Text("From: %s",utf8(t.username).c_str());ImGui::Text("Category: %s",utf8(t.category).c_str());ImGui::TextWrapped("%s",utf8(t.description).c_str());}ImGui::PopID();}if(list.empty())ImGui::TextDisabled("No support messages yet.");ImGui::EndChild();}
    void settings(){ImGui::BeginChild("settingscard",{0,0},true);ImGui::Text("Appearance");const char* themes[]={"Dark","Ocean","Light"};if(ImGui::Combo("Theme",&theme_,themes,3))style();ImGui::Separator();ImGui::Text("Profile avatar");ImGui::TextDisabled(accounts_->avatar_path(user_).empty()?"No avatar selected":"Custom avatar configured");if(ImGui::Button("Choose avatar")){wchar_t p[MAX_PATH]{};if(choose_file(window_,p,OFN_FILEMUSTEXIST|OFN_PATHMUSTEXIST)){try{auto ext=std::filesystem::path(p).extension();auto folder=dir_/L"avatars";std::filesystem::create_directories(folder);auto target=folder/(user_+ext.wstring());std::filesystem::copy_file(p,target,std::filesystem::copy_options::overwrite_existing);accounts_->set_avatar(user_,target.wstring());reload_avatar();notice_="Avatar saved to local profile.";}catch(...){notice_="Unable to save avatar.";}}}ImGui::Separator();ImGui::Text("App settings are stored locally. No Python runtime is used.");ImGui::EndChild();}
    void auth(){ImGui::SetNextWindowPos({0,0});ImGui::SetNextWindowSize(ImGui::GetIO().DisplaySize);ImGui::Begin("##auth",nullptr,ImGuiWindowFlags_NoDecoration|ImGuiWindowFlags_NoMove);ImGui::SetCursorPos({ImGui::GetWindowWidth()/2-190,ImGui::GetWindowHeight()/2-190});ImGui::BeginChild("authcard",{380,370},true);ImGui::TextColored(ImVec4(.3f,.85f,.72f,1),"MAJESTIC AI FISHER");ImGui::TextDisabled("Native workspace");ImGui::Spacing();ImGui::InputText("Login",username_,sizeof(username_));ImGui::InputText("Password",password_,sizeof(password_),ImGuiInputTextFlags_Password);if(ImGui::Button("Sign in",{344,42})){wchar_t u[64]{},p[64]{};MultiByteToWideChar(CP_UTF8,0,username_,-1,u,64);MultiByteToWideChar(CP_UTF8,0,password_,-1,p,64);std::wstring m;if(accounts_->login(u,p,m)){user_=u;login_=false;save_session();reload_avatar();notice_="Welcome back.";}else notice_=std::string(m.begin(),m.end());}if(ImGui::Button("Create account · 3-day trial",{344,36})){wchar_t u[64]{},p[64]{};MultiByteToWideChar(CP_UTF8,0,username_,-1,u,64);MultiByteToWideChar(CP_UTF8,0,password_,-1,p,64);std::wstring m;accounts_->register_user(u,p,m);notice_=std::string(m.begin(),m.end());}if(!notice_.empty())ImGui::TextWrapped("%s",notice_.c_str());ImGui::EndChild();ImGui::End();}
    void render(){style();if(login_)auth();else dashboard();}
};
LRESULT CALLBACK wndproc(HWND h,UINT m,WPARAM w,LPARAM l){if(ImGui_ImplWin32_WndProcHandler(h,m,w,l))return 1;if(m==WM_SIZE&&device&&w!=SIZE_MINIMIZED){destroy_target();swapchain->ResizeBuffers(0,LOWORD(l),HIWORD(l),DXGI_FORMAT_UNKNOWN,0);create_target();return 0;}if(m==WM_DESTROY){PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,w,l);}
int WINAPI WinMain(HINSTANCE instance,HINSTANCE,LPSTR,int){Gdiplus::GdiplusStartupInput startup;ULONG_PTR gdiplus_token=0;Gdiplus::GdiplusStartup(&gdiplus_token,&startup,nullptr);WNDCLASSEXW wc{sizeof(wc),CS_CLASSDC,wndproc,0,0,instance,nullptr,nullptr,nullptr,nullptr,L"MajesticImGui",nullptr};RegisterClassExW(&wc);HWND w=CreateWindowW(wc.lpszClassName,L"Majestic AI Fisher",WS_OVERLAPPEDWINDOW,120,90,1100,700,nullptr,nullptr,instance,nullptr);if(!create_device(w))return 1;create_target();ShowWindow(w,SW_SHOWDEFAULT);IMGUI_CHECKVERSION();ImGui::CreateContext();ImGuiIO& io=ImGui::GetIO();io.Fonts->AddFontFromFileTTF("C:\\Windows\\Fonts\\segoeui.ttf",18,nullptr,io.Fonts->GetGlyphRangesCyrillic());ImGui_ImplWin32_Init(w);ImGui_ImplDX11_Init(device,context);NativeApp app(w);bool done=false;while(!done){MSG msg;while(PeekMessage(&msg,nullptr,0,0,PM_REMOVE)){TranslateMessage(&msg);DispatchMessage(&msg);if(msg.message==WM_QUIT)done=true;}if(done)break;ImGui_ImplDX11_NewFrame();ImGui_ImplWin32_NewFrame();ImGui::NewFrame();app.render();ImGui::Render();const float bg[]={.04f,.05f,.075f,1};context->OMSetRenderTargets(1,&target,nullptr);context->ClearRenderTargetView(target,bg);ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());swapchain->Present(1,0);}ImGui_ImplDX11_Shutdown();ImGui_ImplWin32_Shutdown();ImGui::DestroyContext();destroy_device();DestroyWindow(w);UnregisterClassW(wc.lpszClassName,instance);Gdiplus::GdiplusShutdown(gdiplus_token);return 0;}
